### ISSUE TITLE
Theme GTK apps completely

### ISSUE THREAD

**Issue by Humorist2601** [neuromorph/openbar#66] opened 2024-08-28 00:32 UTC
Hello

This is less of a bug and more of a feature request. Currently you can completely theme gnome-shell using this extension but can only apply an accent to gnome apps. Can there be an option to theme gnome apps completely? Change the background and sidebar color etc

Thank You

**Comment by neuromorph** [comment] 2024-08-28 16:21
Hello,

Yes, not a bug but a feature request. It was on the ToDo list down somewhere but never got to it.  I will look into adding options to select custom colors for Gtk apps :+1:

**Comment by Humorist2601** [comment] 2024-08-28 16:44
Thank you so much for considering the feature

**Comment by neuromorph** [comment] 2024-09-07 15:47
The Gtk section has been updated a bit now and also has options to select custom color as hint for headerbar/sidebar and for view/window. Note that when Autotheming is applied, the Accent color will be set as hint color for Gtk but it can be manually set to any other color.
It is available in `main` branch here on GitHub.
It also includes some other enhancements e.g. ability to interact with panel buttons without having to precisely point on it.
Please try it out by installing the extension by downloading from the main branch and let me know about any feedback you may have.

**Comment by neuromorph** [comment] 2024-09-21 16:07
The new version v41 with support for Gnome 47 and fix for this issue is now live!

Feel free to log a new issue for anymore specific requirements or reopen for any feedback you may have.

**Closed by neuromorph** 2024-09-21 16:07 UTC
