### ISSUE TITLE
GNOME 45 Support

### ISSUE THREAD

**Issue by jcmolinajr** [neuromorph/openbar#1] opened 2023-12-07 02:06 UTC
Any plans to support GNOME 45?

**Comment by neuromorph** [comment] 2023-12-07 06:05
Certainly! I will work out the Gnome 45 version soon. 

Thanks for writing, stay tuned.

**Comment by huseyingulec** [comment] 2023-12-18 16:28
+1

**Comment by neuromorph** [comment] 2023-12-25 18:48
Quick update:
New version for Gnome 45 is almost ready in github main branch if you would like to try out (includes support for menus).
I would like to do a bit more tests and then submit to Gnome extensions-web. Also, the Gnome review might take some time before it can be published.
It should work fine but if you face any issues feel free to ping here.
Note: the default settings may not be good, as I haven't specifically set them yet (likely to be mostly just white color :)

**Comment by jcmolinajr** [comment] 2023-12-25 19:41
Got this error after installing 

` JS ERROR: TypeError: notifSection is null
                                             applyMenuStyles/<@file:///home/<redacted>/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:203:47
                                             applyMenuStyles@file:///home/<redacted>/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:177:59
                                             updatePanelStyle@file:///home/<redacted>/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:286:14
                                             updatePanelStyle/this.updateTimeoutId<@file:///home/<redacted>/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:274:22
                                             setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9
                                             @resource:///org/gnome/shell/ui/init.js:21:20
`

**Comment by neuromorph** [comment] 2023-12-26 04:10
Oops. Please let me know your system details (precise OS/Gnome, versions) and steps to reproduce this error. From the error message I can tell that you would have faced it when coming out from Overview mode. I am testing in a VM with Fedora 39_1.5 (Gnome 45.2) and not getting the error. Once I reproduce, I will be able to fix it.

Thank you for trying out!

**Comment by neuromorph** [comment] 2023-12-26 13:07
Update:
I have added some more finishes in git. I am still unable to reproduce that error but I have also added a fix to what maybe causing it and hopefully it will be resolved now.
Let me know how it goes.
Thank you.

**Comment by jcmolinajr** [comment] 2023-12-26 13:31
Sorry for the delay. I did various tests and despite getting the error message I'm able to use the extension to successfully modify the top panel.

![Screenshot from 2023-12-26 09-28-54](https://github.com/neuromorph/openbar/assets/6530488/9941bdc9-6b30-4cc5-8439-948dfbedee31)

I'm using: 

- Arch Linux
- GNOME Shell 45.2

Where I certainly not the best test case is that I've got quite a lot of extensions installed:

- Alphabetical App Grid
- Arch Linux Updates Indicator
- Blur my Shell
- ddterm
- Expandable Notifications
- Focus Follows Workspace
- Forge
- GNOME Fuzzy App Search
- GSConnect
- Happy Appy Hotkey
- Just Perfection
- PiP on top
- Quick Close in Overview
- Quick Settings Audio Panel
- Rounded Window Corners
- Space Bar
- Thinkpad Battery Threshold
- Transparent Window Moving
- Unmess
- User Themes


Here's the latest error message from the latest version:

`JS ERROR: Exception in callback for signal: hidden: TypeError: this.notifList is undefined
                                           applyMenuStyles@file:///home/<redacted>/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:197:25
                                           updatePanelStyle@file:///home/<redacted>/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:267:14
                                           connect/<.id<@file:///home/<redacted>/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
                                           _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                           _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                           _changeShownState@resource:///org/gnome/shell/ui/overview.js:314:14
                                           _hideDone@resource:///org/gnome/shell/ui/overview.js:651:18
                                           _animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:636:55
                                           onStopped@resource:///org/gnome/shell/ui/overviewControls.js:750:21
                                           _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:84:22
                                           _easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:250:60
                                           @resource:///org/gnome/shell/ui/init.js:21:20`

`JS ERROR: TypeError: this.notifList is undefined
                                           applyMenuStyles@file:///home/<redacted>/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:197:25
                                           updatePanelStyle@file:///home/<redacted>/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:267:14
                                           updatePanelStyle/this.updateTimeoutId<@file:///home/<redacted>/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:256:22
                                           setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9
                                           @resource:///org/gnome/shell/ui/init.js:21:20
`

I went ahead and disabled all other extensions and still get the "this.notifList is undefined' error message.

Again. Thanks for all your work!

**Comment by jcmolinajr** [comment] 2023-12-26 13:40
The culprit was the extension Quick Settings Audio Panel https://extensions.gnome.org/extension/5940/quick-settings-audio-panel/. Disabling it removed the error message.

**Comment by neuromorph** [comment] 2023-12-26 13:54
The Audio Panel one is for Quick Settings, so it may not be the culprit for that error. In case it was causing another error, please let me know.
From the list, I would expect the Expandable Notifications extension to cause that error since it basically overrides the Gnome's notification panel with its own layout. 
I haven't used or looked into any of these two extensions so not sure of details but will check as possible.

Thanks for your inputs!

**Comment by neuromorph** [comment] 2023-12-26 15:15
So, I looked into it. You were right about Audio Panel extension (weird though). I have added a fix in github and tested in VM, both extensions should work OK now with Openbar.

Thanks for reporting.

**Comment by neuromorph** [comment] 2023-12-28 06:31
Note:  I kept Expandable Notifications enabled and noticed that it adds a border to the notifications which feels out pf place. It can be disabled by adding below line to its stylesheet.css file
` border-color: transparent !important;`

Update:
Gnome 45 version is up in Extensions web ! 
Thus, I am closing this issue, if you guys face any problems please raise a new issue.
Thanks!

**Closed by neuromorph** 2023-12-28 06:31 UTC
