### ISSUE TITLE
TypeError: btn.child is null

### ISSUE THREAD

**Issue by Mateuszm126** [neuromorph/openbar#9] opened 2024-01-26 06:59 UTC
TypeError: btn.child is null
![Screenshot from 2024-01-26 07-57-16](https://github.com/neuromorph/openbar/assets/26273710/38a187c0-cf7a-48ae-bda1-3e5c1b1fdd95)
To get rid of it, log out, log in.

**Comment by neuromorph** [comment] 2024-01-26 07:15
Can you please run the following command in a terminal and then install the extension? The journal will show more detailed error message, please paste that here (mainly it'll show the line number). 
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat` 

I have an idea what might be wrong but this will help to confirm. Meanwhile I will get that thing fixed.

Thank you for reporting!

**Comment by neuromorph** [comment] 2024-01-26 07:31
Please also mention what other extensions you are using, esp. the ones that deal with the Top panel. (I am unable to reproduce the issue here but it could be an edge case that can occur with some setups so I'll fix it).

**Comment by mkalinski** [comment] 2024-01-26 08:43
I have a similar issue, with the error saying `btn.child is undefined`. I was trying to identify another extension that could be causing this, by disabling them one by one, but did not succeed.

The error seems to happen randomly when enabling extensions (after they were disabled) in the extension app, or by unlocking screen after locking it. So far I haven't seen this happen on log-in with extensions enabled.

**Comment by neuromorph** [comment] 2024-01-26 09:00
Thank you @mkalinski for the update !
Here's a hotfix patch. You can try it out by using following command. After running the command, you need to logout and login to refresh Gnome/extension.

`cd ~/.local/share/gnome-shell/extensions/openbar@neuromorph/; curl -LJO https://raw.githubusercontent.com/neuromorph/openbar/main/extension.js; cd`

This should fix the issue. Let me know how it goes.

**Comment by neuromorph** [comment] 2024-01-26 11:39
I have also published new version with the fix so you might as well update the extension.
Note: when you upgrade the extension, the stylesheet will be replaced by default so you need to click 'Apply Menu Styles' button or change some other setting in the extension to refresh stylesheet with your saved settings.

**Comment by mkalinski** [comment] 2024-01-26 16:19
I have used this patched version for a whole day, and haven't seen the problem reoccurring. But since it was happening randomly, it's hard to say yet if it's a definitive fix.

**Comment by neuromorph** [comment] 2024-01-26 17:32
Thank you for the update! 
I do believe it's fixed. I will keep the issue open for a while so feel free to comment if it recurs.

**Comment by neuromorph** [comment] 2024-02-04 05:17
Resolved in v13/v14, closing it.

**Closed by neuromorph** 2024-02-04 05:17 UTC
