### ISSUE TITLE
[BUG]: Menu styles are broken

### ISSUE THREAD

**Issue by vishnup95** [neuromorph/openbar#72] opened 2024-09-15 17:15 UTC
**Describe the bug**
Running Fedora 40 with Gnome 46 on wayland. The latest update to v39 broke the rendering of the popup menus somewhat. 

![Screenshot from 2024-09-15 22-34-06](https://github.com/user-attachments/assets/777fa9d4-66de-48a4-baf7-ea03034b7fdd)

**To Reproduce**
Install the latest v39, turn on `Enable Menu Styles` in Popup Menu section
Toggle it off to fix the style issues. 

**Relevant  Specs:**
 - Open Bar version: v39
 - Gnome version: 46	
 - OS/Distribution: Fedora
 - Other installed extensions if interference is expected [Optional]: -

**Screenshots**
Attached above. 

**Error Stack Trace**
No error as such, styling issue(?). Let me if this can be helpful. Will add it.

**Comment by neuromorph** [comment] 2024-09-15 17:41
Hello,

Please elaborate on the exact issue to get a better idea. From the screenshot it looks like the WiFi button is the issue as in the button is not having the Accent color as expected even though the associated 'arrow' is showing correctly.
Is that the issue you are referring to? and how to reproduce it?  
Especially, what do you mean by 'Toggle it off to fix the style issues.'
The Enable Menu Styles in Popup Menu section is added as an option to either style the menus or not. Some users wanted to to only style the bar but not the menus. 

It is tested on Fedora with Gnome 46 and haven't faced a scenario as above. Are you also using a User Theme? If so, can you please try with the user theme disabled?

Thank you for reporting!

**Comment by vishnup95** [comment] 2024-09-15 18:51
Thanks for the reply!

> Hello,
> 
> Please elaborate on the exact issue to get a better idea. From the screenshot it looks like the WiFi button is the issue as in the button is not having the Accent color as expected even though the associated 'arrow' is showing correctly. Is that the issue you are referring to? and how to reproduce it? Especially, what do you mean by 'Toggle it off to fix the style issues.' The Enable Menu Styles in Popup Menu section is added as an option to either style the menus or not. Some users wanted to to only style the bar but not the menus.

Not just the wifi button, please look at the bluetooth icon, font rendering of 100%, Night Light, Dark Mode. All these doesn't look normal. Same with Date Popup menu

Notice the text like Add world clocks in the below screen shots. 
![image](https://github.com/user-attachments/assets/13f5448b-e069-49d7-a633-826417306f70)

Toggle the Enable Menu styles option off i.e go back to the default gnome styles and the font rendering issues dissappear. 

Same menu with Enable Menu styles turned off:

![image](https://github.com/user-attachments/assets/e73e195f-a026-4b8a-86c2-4183637337a0)


Which is what led me to believe that the issue is due to something the extension is doing. 

> 
> It is tested on Fedora with Gnome 46 and haven't faced a scenario as above. Are you also using a User Theme? If so, can you please try with the user theme disabled?

 No themes. Just the default ones. 

> Thank you for reporting!

Thank you for the extension btw! It's a wonderful addition to the gnome desktop space!

NB: In menu styles the only option I use the Auto FG color one. This came up after v39 update today?

**Comment by neuromorph** [comment] 2024-09-15 19:11
> Not just the wifi button, please look at the bluetooth icon, font rendering of 100%, Night Light, Dark Mode. All these doesn't look normal. Same with Date Popup menu

I thought that might be issue with the screenshot. This is certainly unexpected. Open Bar does not alter menu fonts, mainly just colors. The arrows in the buttons also look pointing downwards a bit which I thought maybe a theme but it's not like that in the default screenshot.

> In menu styles the only option I use the Auto FG color one. This came up after v39 update today?

No, it's there from before. You can also try turning it off though.

Are you using fractional scaling or any display scaling? 
Need to figure out a way to reproduce it. I am not facing it in Fedora or Ubuntu.

**Comment by vishnup95** [comment] 2024-09-16 03:34
> > Not just the wifi button, please look at the bluetooth icon, font rendering of 100%, Night Light, Dark Mode. All these doesn't look normal. Same with Date Popup menu
> 
> I thought that might be issue with the screenshot. This is certainly unexpected. Open Bar does not alter menu fonts, mainly just colors. The arrows in the buttons also look pointing downwards a bit which I thought maybe a theme but it's not like that in the default screenshot.
> 
> > In menu styles the only option I use the Auto FG color one. This came up after v39 update today?
> 
> No, it's there from before. You can also try turning it off though.
> 
> Are you using fractional scaling or any display scaling? Need to figure out a way to reproduce it. I am not facing it in Fedora or Ubuntu.

Aah. I run Fedora 40(gnome 46). Wayland display server. Like I said the issue popped up after the update yesterday. Still same after turning off Auto FG color. Let me know if the extension logs/stack trace could be helpful.

**Comment by neuromorph** [comment] 2024-09-17 06:50
> I run Fedora 40(gnome 46). Wayland display server.

I could not reproduce the issue with same setup in a VM so I tried messing around with the config to recreate it. I was able to finally see it and I have one main suspect - the 'Vertical Padding' under 'Bar Highlights' tab. A secondary suspect is Blur My Shell but maybe not (try turning it off in case following doesn't work):

Change the value for the Vertical Padding and keep it whole number e.g. 4.0 or 5.0 etc and it should work. Some fractions seem to cause the issue,  though it may depend on the Display Scaling in use. Currently, I have kept fractional increments in the value even though for 100% scaling, they should get rounded up but I thought for fractional scaling it may help. 
Anyway, try adjusting this setting and see if the problem goes away. It worked for me. Do let me know what you find in your trials i.e. what values seem to cause the issue. I specifically faced the issue for numbers ending in '.5'. 
I will then change the increment for this setting to maybe whole numbers like 1px, 2px etc.

**Comment by JosephM0on** [comment] 2024-09-17 10:34
Good morning
I have the same problem, I will share some images.

![Menu1_ativo](https://github.com/user-attachments/assets/7b97678b-0c23-4813-97dc-faf2e14d82b5)
![Menu1_normal](https://github.com/user-attachments/assets/c357154a-29ea-4cb7-9ab4-314d718a1964)
![right_click_ativo](https://github.com/user-attachments/assets/f33adb7a-0fcc-4db1-a451-2e87f8661da2)
![Right_Click_normal](https://github.com/user-attachments/assets/f40f0cb3-7eb3-4f01-abb2-4565c51c9914)

I don't know what I have to send to help you
Thank you

**Comment by neuromorph** [comment] 2024-09-17 12:53
@vishnup95 , @JosephM0on 

hey guys,

I have added a fix to this issue in the GitHub `main` branch. Can you please install the extension manually from there and test it out. It was linked to the vertical padding but indirectly, this fix should make them decoupled so any setting should be OK.

Let me know.
Thank you!

**Comment by JosephM0on** [comment] 2024-09-17 19:24
@neuromorph 

Hey, Sorry for the delay in responding, I was working.
Yes, I'm already testing it, it works perfectly. Thank you very much

**Comment by vishnup95** [comment] 2024-09-19 05:00
> @vishnup95 , @JosephM0on
> 
> hey guys,
> 
> I have added a fix to this issue in the GitHub `main` branch. Can you please install the extension manually from there and test it out. It was linked to the vertical padding but indirectly, this fix should make them decoupled so any setting should be OK.
> 
> Let me know. Thank you!

Can confirm this fixes the reported issue. Thanks. How do I go back to using the gnome-extensions version now? Delete the files in the gnome-extensions directory and install once again?

**Comment by neuromorph** [comment] 2024-09-19 05:07
> Can confirm this fixes the reported issue. 

Thank you for the update!

> How do I go back to using the gnome-extensions version now?

Why do you want to do that? That will reintroduce the issue. I will release next version soon with this fix and more and at that point your manual installation will also get the update.
If you do want to revert then you can just uninstall and reinstall using Extension Manager also.

**Comment by vishnup95** [comment] 2024-09-19 06:41
> > Can confirm this fixes the reported issue.
> 
> Thank you for the update!
> 
> > How do I go back to using the gnome-extensions version now?
> 
> Why do you want to do that? That will reintroduce the issue. I will release next version soon with this fix and more and at that point your manual installation will also get the update. If you do want to revert then you can just uninstall and reinstall using Extension Manager also.

Ooh sorry, I meant that I wanted to use the published version when the fix is released on that channel. For that, can I just remove the cloned extension from `local` directory and install from gnome-extension website.

**Comment by neuromorph** [comment] 2024-09-19 07:25
Yes, you can do that but not really needed. The new version will be v40 and your current cloned version is v39, so it will automatically get updated as usual.

**Comment by neuromorph** [comment] 2024-09-21 15:56
The new version v41 with support for Gnome 47 and fix for this issue is now live!

**Closed by neuromorph** 2024-09-21 15:56 UTC
