### ISSUE TITLE
[QUESTION] how does the "apply in overview" feature work?

### ISSUE THREAD

**Issue by JE-Amouel** [neuromorph/openbar#37] opened 2024-06-02 11:12 UTC
HI,
I tried to deactivate "apply to overview" thinking that the entire applied style would change to a transparent style, but in fact when I do it, it's only the bar style that changes, I use a trisland bar style , and when I deactivate the "apply in overview" option, when I go to overview the bar style changes to an island style instead of being transparent.

how to solve that? it's a Bug?

THANKS.

**Comment by neuromorph** [comment] 2024-06-02 11:31
Yes, the entire bar would be transparent but menu styles will remain.
e.g.

![normal](https://github.com/neuromorph/openbar/assets/4656768/83b741ef-22a2-4b57-9976-76af60e251a4)
![overview](https://github.com/neuromorph/openbar/assets/4656768/be29283e-afad-46e4-a6b4-3e9ef94ca7a6)

Gnome 42? Are you on latest commit from 'g42-44'? Post your pics to see whats happening.

**Comment by JE-Amouel** [comment] 2024-06-02 12:57
my bad :disappointed: ,
I installed the wrong version the first time,

it works very well for the g42-44 branch :+1: 

![Ubuntu 64-bit-2024-06-02-14-09-45](https://github.com/neuromorph/openbar/assets/146543282/28810523-431f-4bc5-a825-1f4c5bad5e08)

just a question in passing,
regardless of the type of bar,
how can I set a distance between the panel and the edge of the screen (floating panel), I would like to have the possibility to manually set this value.

THANK YOU.

**Comment by neuromorph** [comment] 2024-06-02 13:51
Cool! BTW, there's been some update yesterday and today but not in g42-44, I will port it soon.

What is this "How do LLMs work?" Wallpaper or something else?

> how can I set a distance between the panel and the edge of the screen (floating panel), I would like to have the possibility to manually set this value.

You can do it from Top Bar Properties, with 'Bar Margins'. It will apply to any type of Bar except 'Mainland' since it is by definition 'not floating'.

**Comment by JE-Amouel** [comment] 2024-06-02 14:48
>You can do it from Top Bar Properties, with 'Bar Margins'. It will apply to any type of Bar except 'Mainland' since it is by definition 'not floating'.

yes I did it, but my panel goes down every time I increase it.
as the layout of my panel with is at the bottom, when I increase "Bar Margin" it goes down to the bottom until it disappears, so I set it to zero.

**Comment by neuromorph** [comment] 2024-06-02 15:06
> as the layout of my panel with is at the bottom, when I increase "Bar Margin" it goes down to the bottom until it disappears, so I set it to zero.

That should not happen, it would be a regression bug in that case. However, this only applies if the 'Position of Bar' is selected as Bottom in Top Bar Properties. If bar is set to bottom from external means (using another extension) then Open Bar thinks it is still top and so it is not a bug. Technically additional checks can be added but there are already many since people are moving the bar to different monitors and what not. Try setting position to bottom if it is set to Top. If still problem persists let me know.
Do a few tests to try some scenarios, not sure what exactly. Just to confirm if it works. This is since if two different extensions are trying to set the position then there will be some conflict.
If it still does not work, then Dash to Panel is probably overriding it. In that case it may have some settings to adjust the gap though I am not sure. 
As a last resort, I will need to think about the additional checks to figure out where the bar is in a multi monitor scenario with random layouts.

**Comment by JE-Amouel** [comment] 2024-06-02 15:55
THANKS :pray:

**Comment by neuromorph** [comment] 2024-06-03 04:15
> THANKS 🙏

What do you mean? Did it work and if so how did you make it work?

**Comment by JE-Amouel** [comment] 2024-06-03 13:57
>What do you mean? Did it work and if so how did you make it work?

I tried several things, but it doesn't work with dash to panel.
Everything works correctly only for the original panel.
I think I'll just enjoy my desktop with the option that works best, and it's already perfect.

**Comment by neuromorph** [comment] 2024-06-20 14:33
Marking the issue as resolved to the extent possible and closing here.
Thanks.

**Closed by neuromorph** 2024-06-20 14:33 UTC
Labels: question

**Comment by JE-Amouel** [comment] 2024-06-24 11:17
Very exited to check all the new features, 
Thank you.
