### ISSUE TITLE
btn.child is null

### ISSUE THREAD

**Issue by nw0p** [neuromorph/openbar#47] opened 2024-06-21 23:22 UTC
logging in and out fixes this issue, but it keeps happening, seemingly randomly, very inconvenient, dunno what could be causing it 
![Screenshot from 2024-06-21 19-22-04](https://github.com/neuromorph/openbar/assets/38057139/62a19c31-8ddc-4c3f-aee4-3efee24a3f85)

**Comment by neuromorph** [comment] 2024-06-22 05:09
Hello,

Please specify your Gnome version and OpenBar version.
Also, some fixes have been added for similar issue in GitHub. You can download (or git clone) the extension from GitHub and check if that fixes the issue (likely it will). Manual installation is needed.

Please download from following GitHub branch:
For Gnome 42-44: branch 'g42-44'
For Gnome 45-46: branch 'main' 

NOTE: After the manual install of GitHub code, you need to logout and login again for the changes to take effect.
  

In case the issue persists even after above steps, please run the following command in a terminal and then Enable the extension. If the error is preventing the extension from enabling then just remove and install the extension again while the command is running. If there is no error during enable then keep the command running and try disabling the extension. At some point the same error will show up in the terminal but it will also have a trace log. Please share that here so we can debug the issue.

`SHELL_DEBUG=all journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

Thank you for reporting!

**Comment by juarezr** [comment] 2024-06-22 05:10
## Reproducible test case

I've found a reproducible test case:

1. Install the extensions openbar and [blur-my-shell]()
2. Disable both.
3. Log out/Log in or reboot
4. Enable the **blur-my-shell** extension first
5. Enable the **openbar** extension

After this I get the error:

> Extension openbar@neuromorph: TypeError: btn.child is undefined

## Information

<details>
  <summary>Gnome Shell Logs</summary>

```bash
❯ journalctl --output=short-delta --no-hostname --no-pager --since='5 minute ago' /usr/bin/gnome-shell

[41512.826340                ] gnome-shell[17770]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
[41567.299685 <   54.473345 >] gnome-shell[17770]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
[41677.242039 <  109.942354 >] gnome-shell[17770]: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
[41677.242292 <    0.000253 >] gnome-shell[17770]: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
[41755.939796 <   78.697504 >] gnome-shell[17770]: Extension openbar@neuromorph: TypeError: btn.child is undefined
                                                   
                                                   Stack trace:
                                                     enable@file:///home/juarezr/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:1095:20
                                                     _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:267:38
                                                     async*_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:631:24
                                                     _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:736:18
                                                     createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
                                                     enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:290:29
                                                     EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:453:38
                                                     _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
                                                     _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
                                                     @resource:///org/gnome/shell/ui/init.js:21:20
```
</details>

<details>
  <summary>Extensions Enabled</summary>

```bash
❯ dconf list /org/gnome/shell/extensions/ | xargs -i sh -c 'printf "\n[{}]\n" && dconf dump /org/gnome/shell/extensions/{} | tail -n +2'

blur-my-shell@aunetx
  Name: Blur my Shell
  URL: https://github.com/aunetx/blur-my-shell
  Version: 62
  Enabled: Yes
  State: ACTIVE

clipboard-indicator@tudmotu.com
  Name: Clipboard Indicator
  URL: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator
  Version: 62
  Enabled: Yes
  State: ACTIVE

notification-banner-reloaded@marcinjakubowski.github.com
  Name: Notification Banner Reloaded
  URL: https://github.com/marcinjakubowski/notification-position-reloaded
  Version: 11
  Enabled: Yes
  State: ACTIVE

switcher@landau.fi
  Name: Switcher
  URL: https://github.com/daniellandau/switcher
  Version: 41
  Enabled: Yes
  State: ACTIVE

onedrive@client.onedrive.com
  Name: Onedrive Client
  URL: https://github.com/dvmasterfx/Onedrive-Gnome-Shell-45
  Version: 8
  Enabled: Yes
  State: ACTIVE

user-theme@gnome-shell-extensions.gcampax.github.com
  Name: User Themes
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Version: 58
  Enabled: Yes
  State: ACTIVE

mediacontrols@cliffniff.github.com
  Name: Media Controls
  URL: https://github.com/cliffniff/media-controls
  Version: 2.0.1 (36)
  Enabled: Yes
  State: ACTIVE

mute-unmute@mcast.gnomext.com
  Name: Mute/Unmute
  URL: https://github.com/ihpled/mute-unmute
  Version: 18
  Enabled: Yes
  State: ACTIVE

forge@jmmaranan.com
  Name: Forge
  URL: https://github.com/forge-ext/forge
  Version: 83
  Enabled: Yes
  State: ACTIVE

notification-icons@muhammad_ans.github
  Name: Top Panel Notification Icons Revived
  URL: https://github.com/muhammad-ans/notification-icons
  Version: 5
  Enabled: Yes
  State: ACTIVE

advanced-alt-tab@G-dH.github.com
  Name: AATWS (Advanced Alt-Tab Window Switcher)
  URL: https://github.com/G-dH/advanced-alttab-window-switcher
  Version: 46.2 (55)
  Enabled: Yes
  State: ACTIVE

window-title-is-back@fthx
  Name: Window title is back

 Options in preferences UI: toggle items, colored icon, icon size.
  URL: https://github.com/fthx/window-title-is-back
  Version: 29
  Enabled: Yes
  State: ACTIVE

lockkeys@vaina.lt
  Name: Lock Keys
  URL: https://github.com/kazysmaster/gnome-shell-extension-lockkeys
  Version: 57
  Enabled: Yes
  State: ACTIVE

openweather-extension@penguin-teal.github.io
  Name: OpenWeather Refined
  URL: https://github.com/penguin-teal/gnome-openweather
  Version: 136 (15)
  Enabled: Yes
  State: ACTIVE

appindicatorsupport@rgcjonas.gmail.com
  Name: AppIndicator and KStatusNotifierItem Support
  URL: https://github.com/ubuntu/gnome-shell-extension-appindicator
  Version: 58
  Enabled: Yes
  State: ACTIVE

Bluetooth-Battery-Meter@maniacx.github.com
  Name: Bluetooth Battery Meter
  URL: https://github.com/maniacx/Bluetooth-Battery-Meter
  Version: 16
  Enabled: Yes
  State: ACTIVE
```

</details>


<details>
  <summary>Extensions Settings</summary>

```bash
❯ dconf list /org/gnome/shell/extensions/ | xargs -i sh -c 'printf "\n[{}]\n" && dconf dump /org/gnome/shell/extensions/{} | tail -n +2'

[blur-my-shell/]
pipelines={'pipeline_default': {'name': <'Default'>, 'effects': <[<{'type': <'native_static_gaussian_blur'>, 'id': <'effect_000000000000'>, 'params': <{'radius': <30>, 'brightness': <0.59999999999999998>}>}>]>}, 'pipeline_default_rounded': {'name': <'Default rounded'>, 'effects': <[<{'type': <'native_static_gaussian_blur'>, 'id': <'effect_000000000001'>, 'params': <{'radius': <30>, 'brightness': <0.59999999999999998>}>}>, <{'type': <'corner'>, 'id': <'effect_000000000002'>, 'params': <{'radius': <24>}>}>]>}, 'pipeline_24585052809655': {'name': <'Transparent'>, 'effects': <[<{'type': <'native_static_gaussian_blur'>, 'id': <'effect_12156049563396'>, 'params': <{'brightness': <0.90000000000000002>, 'unscaled_radius': <4>}>}>]>}}
settings-version=2

[Bluetooth-Battery-Meter/]
enable-battery-level-text=true
paired-supported-device-list=['{"path":"/org/bluez/hci0/dev_E7_67_D8_21_EE_F5","icon":"input-mouse","alias":"M720 Triathlon","paired":true,"battery-enabled":true,"indicator-enabled":true}', '{"path":"/org/bluez/hci0/dev_60_F4_3A_0E_34_AC","icon":"audio-headset","alias":"EDIFIER W828NB","paired":true,"battery-enabled":true,"indicator-enabled":true}']
swap-icon-text=false

[advanced-alt-tab-window-switcher/]
app-switcher-popup-hide-win-counter-for-single-window=true
app-switcher-popup-icon-size=128
app-switcher-popup-raise-first-only=true
app-switcher-popup-search-pref-running=true
app-switcher-popup-titles=true
hot-edge-fullscreen=false
super-key-mode=3
switcher-popup-hot-keys=true
switcher-popup-monitor=3
switcher-popup-preview-selected=1
switcher-popup-status=true
switcher-popup-theme=0
switcher-popup-up-down-action=3
switcher-ws-thumbnails=1
win-switcher-popup-filter=1
win-switcher-popup-order=1
win-switcher-popup-preview-size=256

[appindicator/]
icon-opacity=255
icon-size=24
legacy-tray-enabled=true

[appfolder]
brightness=0.59999999999999998
sigma=30

[applications]
blur=true
brightness=0.75
enable-all=true
sigma=15
whitelist=@as []

[dash-to-dock]
blur=false
brightness=0.59999999999999998
pipeline='pipeline_default_rounded'
sigma=30
static-blur=true
style-dash-to-dock=0

[lockscreen]
pipeline='pipeline_default'

[overview]
pipeline='pipeline_default'
style-components=3

[panel]
blur=false
brightness=0.48999999999999999
force-light-text=false
pipeline='pipeline_24585052809655'
sigma=4
static-blur=true
style-panel=3
unblur-in-overview=false

[screenshot]
blur=true
pipeline='pipeline_default'

[window-list]
brightness=0.59999999999999998
sigma=30

[clipboard-indicator/]
clear-history=@as []
clear-on-boot=true
history-size=27
move-item-first=true
pinned-on-bottom=true
private-mode-binding=@as []
toggle-menu=['<Super>backslash']

[custom-accent-colors/]
accent-color='red'
theme-shell=true

[dash-to-dock/]
apply-custom-theme=true
autohide-in-fullscreen=true
dash-max-icon-size=48
dock-fixed=false
extend-height=false
hot-keys=false
max-alpha=0.80000000000000004
min-alpha=0.59999999999999998
running-indicator-dominant-color=true
show-apps-at-top=true
unity-backlit-items=true

[date-menu-formatter/]
apply-all-panels=true
font-size=12
formatter='01_luxon'
pattern='EEEE ┆ d MMM ┆ H : mm'
remove-messages-indicator=false
text-align='center'
update-level=0

[ding/]
check-x11wayland=true
show-home=false

[eye-on-cursor/]
eye-count=2
eye-index=1
eye-line-mode=false
eye-position='center'
eye-shape='eyelid'
tracker-color-default='#f7c38d'
tracker-color-left='#f66151'
tracker-color-middle='#2ec27e'
tracker-color-right='#1c71d8'
tracker-opacity=30

[forge/]
css-last-update=uint32 37
focus-border-toggle=true
move-pointer-focus-enabled=true
stacked-tiling-mode-enabled=false
tabbed-tiling-mode-enabled=false
tiling-mode-enabled=true
window-gap-hidden-on-single=true
window-gap-size=uint32 2

[keybindings]
con-split-horizontal=['<Alt><Super>h']
con-split-layout-toggle=['<Alt><Super>l']
con-split-vertical=['<Alt><Super>v']
con-stacked-layout-toggle=['<Alt><Super>s']
con-tabbed-layout-toggle=['<Alt><Super>t']
con-tabbed-showtab-decoration-toggle=['<Control><Alt>y']
focus-border-toggle=['<Alt><Super>b']
prefs-open=['<Alt><Super>o']
prefs-tiling-toggle=['<Alt><Super>p']
window-focus-down=['<Super>Down']
window-focus-left=['<Super>Left']
window-focus-right=['<Super>Right']
window-focus-up=['<Super>Up']
window-gap-size-decrease=['<Control><Super>minus']
window-gap-size-increase=['<Control><Super>plus']
window-move-down=['<Shift><Super>Down']
window-move-left=['<Shift><Super>Left']
window-move-right=['<Shift><Super>Right']
window-move-up=['<Shift><Super>Up']
window-resize-bottom-decrease=['<Shift><Control><Super>i']
window-resize-bottom-increase=['<Control><Super>u']
window-resize-left-decrease=['<Shift><Control><Super>o']
window-resize-left-increase=['<Control><Super>y']
window-resize-right-decrease=['<Shift><Control><Super>y']
window-resize-right-increase=['<Control><Super>o']
window-resize-top-decrease=['<Shift><Control><Super>u']
window-resize-top-increase=['<Control><Super>i']
window-snap-center=['<Control><Super>3']
window-snap-one-third-left=['<Control><Super>1']
window-snap-one-third-right=['<Control><Super>5']
window-snap-two-third-left=['<Control><Super>2']
window-snap-two-third-right=['<Control><Super>4']
window-swap-down=['<Control><Super>Down']
window-swap-last-active=['<Super>Return']
window-swap-left=['<Control><Super>Left']
window-swap-right=['<Control><Super>Right']
window-swap-up=['<Control><Super>Up']
window-toggle-always-float=['<Shift><Super>f']
window-toggle-float=['<Super>f']
workspace-active-tile-toggle=['<Alt><Super>a']

[lockkeys/]
style='show-hide'

[mediacontrols/]
extension-index=uint32 2
extension-position='Left'
label-width=uint32 550
scroll-labels=false
show-control-icons-next=true
show-control-icons-previous=false
show-control-icons-seek-backward=false
show-control-icons-seek-forward=false
show-label=false

[next-up/]
which-panel=1

[notification-banner-reloaded/]
anchor-horizontal=1
anchor-vertical=0
animation-direction=2
animation-time=500
padding-horizontal=8
padding-vertical=8

[notification-icons/]
colored-icons=true
right-side=false

[openbar/]
accent-color=['0.9647058844566345', '0.3803921639919281', '0.3176470696926117']
accent-override=true
apply-accent-shell=true
apply-all-shell=true
apply-flatpak=true
apply-gtk=true
apply-menu-notif=true
apply-menu-shell=true
auto-bgalpha=false
autofg-bar=true
autofg-menu=true
autohg-bar=true
autohg-menu=true
autotheme='Dark'
autotheme-dark='Dark'
autotheme-font=true
autotheme-light='Pastel'
autotheme-refresh=false
balpha=0.90000000000000002
bartype='Trilands'
bcolor=['0.8784313725490196', '0.807843137254902', '0.7568627450980392']
bg-change=false
bgalpha=0.0
bgalpha-wmax=1.0
bgalpha2=0.90000000000000002
bgcolor=['0.16470588235294117', '0.16862745098039217', '0.2']
bgcolor-wmax=['0.11764705882352941', '0.11764705882352941', '0.11764705882352941']
bgcolor2=['0.3058823529411765', '0.29411764705882354', '0.29411764705882354']
bgpalette=false
bguri='file:///home/juarezr/.config/variety/wallpaper/wallpaper-clock-7d6a20101f0c24be169e0cfce0d3c67a.jpg'
border-wmax=true
bordertype='solid'
boxalpha=0.0
boxcolor=['0.16470588235294117', '0.16862745098039217', '0.2']
bradius=6.0
bwidth=2.0
candy1=['0.15', '0.62', '0.79']
candy2=['0.313', '0.176', '0.945']
candy3=['0.10980392247438431', '0.43921568989753723', '0.8509804010391235']
candy4=['0.8980392217636108', '0.6509804129600525', '0.039215657860040665']
candy5=['0.18', '0.76', '0.49']
candy6=['0.9300000071525574', '0.30000001192092896', '0.5400000214576721']
candy7=['0.5098040103912354', '0.2392156720161438', '0.6117647290229797']
candy8=['1', '0.4705882668495178', '0']
candyalpha=0.75
candybar=true
color-scheme='prefer-dark'
count1=355009
count10=304
count11=268
count12=61
count2=75322
count3=73336
count4=31491
count5=12693
count6=9124
count7=5193
count8=4853
count9=316
cust-margin-wmax=false
dark-accent-color=['0.9647058844566345', '0.3803921639919281', '0.3176470696926117']
dark-bcolor=['0.8784313725490196', '0.807843137254902', '0.7568627450980392']
dark-bgcolor=['0.16470588235294117', '0.16862745098039217', '0.2']
dark-bgcolor-wmax=['0.11764705882352941', '0.11764705882352941', '0.11764705882352941']
dark-bgcolor2=['0.3058823529411765', '0.29411764705882354', '0.29411764705882354']
dark-bguri='file:///home/juarezr/.config/variety/wallpaper/wallpaper-clock-7d6a20101f0c24be169e0cfce0d3c67a.jpg'
dark-boxcolor=['0.16470588235294117', '0.16862745098039217', '0.2']
dark-iscolor=['0.16470588235294117', '0.16862745098039217', '0.2']
dark-mbcolor=['0.5372549019607843', '0.592156862745098', '0.6274509803921569']
dark-mbgcolor=['0.08627450980392157', '0.08627450980392157', '0.08627450980392157']
dark-mhcolor=['0', '0.699999988079071', '0.8999999761581421']
dark-mscolor=['0.9300000071525574', '0.30000001192092896', '0.5400000214576721']
dark-mshcolor=['0', '0', '0']
dark-palette1=['80', '58', '63']
dark-palette10=['99', '120', '101']
dark-palette11=['154', '152', '159']
dark-palette12=['183', '170', '169']
dark-palette2=['146', '62', '54']
dark-palette3=['215', '91', '63']
dark-palette4=['23', '21', '21']
dark-palette5=['244', '198', '149']
dark-palette6=['44', '18', '15']
dark-palette7=['98', '88', '109']
dark-palette8=['56', '33', '17']
dark-palette9=['167', '169', '174']
dark-shcolor=['0', '0', '0']
dark-smbgcolor=['0.3058823529411765', '0.29411764705882354', '0.29411764705882354']
dark-winbcolor=['0.9686274528503418', '0.7647058963775635', '0.5529412031173706']
dashdock-style='Default'
default-font='Sans 12'
extend-menu-shell=true
fgalpha=1.0
fgcolor=['1.0', '1.0', '1.0']
font='Inter Variable Bold 12'
gradient=false
gradient-direction='horizontal'
gtk-popover=true
halpha=0.62
handle-border=3.0
hcolor=['0', '0.7', '0.9']
heffect=false
height=32.0
hpad=1.0
import-export=false
isalpha=0.81000000000000005
iscolor=['0.16470588235294117', '0.16862745098039217', '0.2']
light-bcolor=['0.6862745098039216', '0.5098039215686274', '0.42745098039215684']
light-bgcolor=['0.41568627450980394', '0.4588235294117647', '0.48627450980392156']
light-bgcolor-wmax=['0.9215686274509803', '0.9215686274509803', '0.9215686274509803']
light-bgcolor2=['0.9019607843137255', '0.8588235294117647', '0.8235294117647058']
light-bguri='file:///home/juarezr/.config/variety/wallpaper/wallpaper-clock-60ead6a59d1776ced412946636d0827d.jpg'
light-boxcolor=['0.41568627450980394', '0.4588235294117647', '0.48627450980392156']
light-iscolor=['0.41568627450980394', '0.4588235294117647', '0.48627450980392156']
light-mbcolor=['0.08235294117647059', '0.09803921568627451', '0.10980392156862745']
light-mbgcolor=['0.8784313725490196', '0.8235294117647058', '0.7843137254901961']
light-mscolor=['0.23137254901960785', '0.8627450980392157', '0.8627450980392157']
light-mshcolor=['0', '0', '0']
light-palette1=['80', '58', '63']
light-palette10=['99', '120', '101']
light-palette11=['155', '152', '159']
light-palette12=['183', '170', '169']
light-palette2=['146', '62', '54']
light-palette3=['215', '91', '63']
light-palette4=['23', '21', '21']
light-palette5=['244', '198', '149']
light-palette6=['44', '18', '15']
light-palette7=['98', '88', '109']
light-palette8=['56', '33', '17']
light-palette9=['168', '169', '174']
light-shcolor=['0', '0', '0']
light-smbgcolor=['0.9019607843137255', '0.8588235294117647', '0.8235294117647058']
light-winbcolor=['0.23137254901960785', '0.8627450980392157', '0.8627450980392157']
margin=0.0
margin-wmax=0.0
mbalpha=0.75
mbcolor=['0.5372549019607843', '0.592156862745098', '0.6274509803921569']
mbg-gradient=true
mbgalpha=0.57999999999999996
mbgcolor=['0.08627450980392157', '0.08627450980392157', '0.08627450980392157']
menu-radius=8.0
menustyle=true
mfgalpha=1.0
mfgcolor=['1.0', '1.0', '1.0']
mhalpha=0.45000000000000001
mhcolor=['0', '0.699999988079071', '0.8999999761581421']
monitors='all'
msalpha=0.75
mscolor=['0.9300000071525574', '0.30000001192092896', '0.5400000214576721']
mshalpha=0.16
mshcolor=['0', '0', '0']
neon=true
neon-wmax=true
notif-radius=4.0
palette1=['80', '58', '63']
palette10=['99', '120', '101']
palette11=['154', '152', '159']
palette12=['183', '170', '169']
palette2=['146', '62', '54']
palette3=['215', '91', '63']
palette4=['23', '21', '21']
palette5=['244', '198', '149']
palette6=['44', '18', '15']
palette7=['98', '88', '109']
palette8=['56', '33', '17']
palette9=['167', '169', '174']
pause-reload=false
position='Top'
prominent1=['17', '22', '24']
prominent2=['172', '160', '156']
prominent3=['101', '92', '87']
prominent4=['131', '140', '141']
prominent5=['127', '131', '140']
prominent6=['65', '85', '91']
qtoggle-radius=6.0
radius-bottomleft=true
radius-bottomright=true
radius-topleft=true
radius-topright=true
reloadstyle=false
removestyle=false
set-notifications=true
set-overview=true
set-yarutheme=false
shadow=false
shalpha=0.10000000000000001
shcolor=['0', '0', '0']
sidebar-transparency=true
slider-height=4.0
smbgalpha=0.94999999999999996
smbgcolor=['0.3058823529411765', '0.29411764705882354', '0.29411764705882354']
smbgoverride=true
traffic-light=true
trigger-autotheme=false
trigger-reload=false
variation='Default'
vpad=4.0
width-bottom=true
width-left=true
width-right=true
width-top=true
winbalpha=0.52000000000000002
winbcolor=['0.9686274528503418', '0.7647058963775635', '0.5529412031173706']
wmaxbar=false

[openweatherrefined/]
center-forecast=true
clock-format='24h'
days-forecast=7
delay-ext-init=30
has-run=true
hi-contrast='none'
locs=[(uint32 0, 'Curitiba', uint32 0, '-25.4392623,-49.3015745')]
menu-alignment=53.70454545454546
my-loc-prov='ipinfoio'
position-in-panel='center'
position-index=1
prefs-default-height=1048
prefs-default-width=856
pressure-decimal-places=-1
show-comment-in-panel=true
show-sunsetrise-in-panel=true
show-text-in-panel=true
sun-in-panel-first=false
translate-condition=true
use-system-icons=true
weather-provider='openweathermap'
wind-direction=true

[order-icons/]
order-icons-center=['eye-on-cursor@djinnalexio.github.io0.8490436085779737', 'eye-on-cursor@djinnalexio.github.io0.08501147716909774', 'eye-on-cursor@djinnalexio.github.io0.8514571945762041', 'eye-on-cursor@djinnalexio.github.io0.8287810014399559', 'eye-on-cursor@djinnalexio.github.io0.887951007197327', 'eye-on-cursor@djinnalexio.github.io0.7748243329291365', 'eye-on-cursor@djinnalexio.github.io0.9121699384999417', 'eye-on-cursor@djinnalexio.github.io0.20521965123729602', 'eye-on-cursor@djinnalexio.github.io0.87231761733722', 'eye-on-cursor@djinnalexio.github.io0.3010600329907026', 'eye-on-cursor@djinnalexio.github.io0.1950314951763612', 'eye-on-cursor@djinnalexio.github.io0.3952649240709415', 'eye-on-cursor@djinnalexio.github.io0.14559016369152933', 'eye-on-cursor@djinnalexio.github.io0.6975528366344762', 'eye-on-cursor@djinnalexio.github.io0.7586685018083106', 'eye-on-cursor@djinnalexio.github.io0.8330384608097351', 'eye-on-cursor@djinnalexio.github.io0.011723104792952355', 'eye-on-cursor@djinnalexio.github.io0.33280051012496903', 'eye-on-cursor@djinnalexio.github.io0.37882301161693677', 'dateMenu']
order-icons-left=['eye-on-cursor@djinnalexio.github.io0.023935983815807416', 'eye-on-cursor@djinnalexio.github.io0.34949531933924927', 'activities', 'focused-window-indicator']
order-icons-right=['eye-on-cursor@djinnalexio.github.io0.44309959325189874', 'eye-on-cursor@djinnalexio.github.io0.9567504802230778', 'openWeatherMenu', 'variety', 'onedrive@client.onedrive.com', 'mute-unmute@mcast.gnomext.com', 'clipboardIndicator', 'dwellClick', 'software-update-available', 'livepatch', 'lockkeys', 'keyboard', 'a11y', 'screenSharing', 'screenRecording', 'quickSettings']

[panel-date-format/]
format='%Y.%m.%d %H:%M'

[quick-settings-tweaks/]
datemenu-fix-weather-widget=true
disable-adjust-content-border-radius=true
disable-remove-shadow=false
input-show-selected=false
list-buttons='[{"name":"SystemItem","title":null,"visible":true},{"name":"OutputStreamSlider","title":null,"visible":true},{"name":"InputStreamSlider","title":null,"visible":false},{"name":"St_BoxLayout","title":null,"visible":true},{"name":"BrightnessItem","title":null,"visible":true},{"name":"NMWiredToggle","title":"Wired","visible":true},{"name":"NMWirelessToggle","title":"Wi-Fi","visible":true},{"name":"NMModemToggle","title":null,"visible":false},{"name":"NMBluetoothToggle","title":null,"visible":false},{"name":"NMVpnToggle","title":null,"visible":false},{"name":"BluetoothToggle","title":"Bluetooth","visible":true},{"name":"PowerProfilesToggle","title":"Power Mode","visible":true},{"name":"NightLightToggle","title":"Night Light","visible":true},{"name":"DarkModeToggle","title":"Dark Style","visible":true},{"name":"KeyboardBrightnessToggle","title":"Keyboard","visible":false},{"name":"RfkillToggle","title":"Airplane Mode","visible":true},{"name":"RotationToggle","title":"Auto Rotate","visible":false},{"name":"FeatureMenuToggle","title":"Tiling","visible":true},{"name":"DndQuickToggle","title":"Do Not Disturb","visible":true},{"name":"BackgroundAppsToggle","title":"No Background Apps","visible":false},{"name":"MediaSection","title":null,"visible":false},{"name":"Notifications","title":null,"visible":false}]'
media-control-enabled=true
output-show-selected=false
user-removed-buttons=@as []
volume-mixer-enabled=false

[switcher/]
fade-enable=true
font-size=uint32 18
icon-size=uint32 18
launcher-stats='{"com.mattjakeman.ExtensionManager.desktop":1,"ca.desrt.dconf-editor.desktop":1}'
matching=uint32 1
show-executables=true
show-original-names=false
show-switcher=['<Control>Escape']
workspace-indicator=true

[tiling-assistant/]
active-window-hint-color='rgb(211,70,21)'
disable-tile-groups=false
enable-tiling-popup=true
last-version-installed=46
tiling-popup-all-workspace=true

[user-theme/]
name='Yaru-red-dark'

[weatherornot/]
position='clock-right-centered'

[window-title-is-back/]
colored-icon=true
show-app=false
```

</details>


<details>
  <summary>System Information</summary>

```bash
❯ cat /etc/os-release && uname -a | grep '='

PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

</details>

**Comment by neuromorph** [comment] 2024-06-22 05:17
@juarezr 
Thank you for the log. This is same issue as #42 . It has been fixed in GitHub and fix will be part of next update soon.
Please follow comment above to install the updated version right away from the correct branch.

Note: The manual install is straightforward but check the ReadMe for the instructions, if needed.

**Comment by neuromorph** [comment] 2024-06-22 18:01
Hey  @nw0p and @juarezr 

Hope the issue is fixed for you with the install from GitHub code. Let me know if it's resolved or are you still facing some issue. I will be uploading the next update soon and just want to make sure all fixes are part of it.

Thank you!

**Comment by neuromorph** [comment] 2024-06-24 04:58
The update with fixes is already live on Gnome Extensions web so closing this issue. If you face any problems, feel free to reopen or log a new issue.

**Closed by neuromorph** 2024-06-24 04:58 UTC
