### ISSUE TITLE
Does Nothing

### ISSUE THREAD

**Issue by in4matix** [neuromorph/openbar#2] opened 2023-12-14 16:46 UTC
Not sure if I'm missing something, but it does not work at all?

**Comment by neuromorph** [comment] 2023-12-15 05:44
Hello Danny,

Please provide more details. I will need to be able to reproduce the issue you are facing so it can be fixed.
- Gnome version? ( I guess 42.x but let me know).
- Please verify that the extension is enabled or if it encountered an error (you can check with Extension Manager or Glass Grid)
- If successfully enabled, open settings and add border width, color, alpha etc so it is easier to see changes. Then try changing Bar Type.
- Make sure the alpha values for colors aren't zero (transparent) when changing colors.
- What you finally see will depend on the selected settings. Finer control means that you would need to make sensible choices.

Note: For Menus, next version will provide better support

**Comment by in4matix** [comment] 2023-12-15 08:21
Hello,

I'm on Ubuntu 22 LTS - Gnome 42.9 . Extension is enabled. Also use Blur My Shell Extension.

![Screenshot from 2023-12-15 10-18-01](https://github.com/neuromorph/openbar/assets/62904593/f93f95ee-2e5a-4dbd-b208-b1e6ffc5bff3)
![Screenshot from 2023-12-15 10-18-13](https://github.com/neuromorph/openbar/assets/62904593/3ef782c4-1388-4b2d-9a75-5e50e65d80a6)
![Screenshot from 2023-12-15 10-18-29](https://github.com/neuromorph/openbar/assets/62904593/dec3a8ba-30d0-498f-9ef8-92f52ee1cb68)
![Screenshot from 2023-12-15 10-18-39](https://github.com/neuromorph/openbar/assets/62904593/2f693182-a021-403c-be1f-97cf0cf63208)

**Comment by in4matix** [comment] 2023-12-15 08:24
I have tried many different setting and even after logging out and back in, no changes. I also tried setting the Gnome shell to default using Tweak Tool.

**Comment by neuromorph** [comment] 2023-12-15 10:26
I am also on Ubuntu LTS with G 42.9 so this is unexpected. Your extension settings seem fine. Also, you've tested with default gnome shell theme so custom theme shouldn't be an issue.
In any case, not seeing any change in Top bar by changing the extension settings points mainly to the issue that the extension is Not enabled successfully. 
Run this command in terminal to see if extension appears in enabled list:
`gnome-extensions list --enabled`

Then, disable the extension through some tool or with command 
`gnome-extensions disable openbar@neuromorph`
and in the terminal run following command to monitor the logs
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

Now, enable the extension again using a tool or this command
`gnome-extensions enable openbar@neuromorph`

Watch the log in the journalctl command tab. If you see any error for openbar, let me know.

**Comment by in4matix** [comment] 2023-12-15 11:29
This is what I'm getting:

```
daniel@dkdt:~$ journalctl /usr/bin/{gjs,gnome-shell} -fo cat
Number Object : [4]
Number Object : [4]
Number Object : [4]
Number Object : [4]
Number Object : [4]
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Source ID 687165 was not found when attempting to remove it
Source ID 755588 was not found when attempting to remove it
Source ID 727674 was not found when attempting to remove it
Source ID 796339 was not found when attempting to remove it
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
JS ERROR: TypeError: btn.child.menu is null
resetStyle@/home/daniel/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:75:21
updateStyle@/home/daniel/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:173:14
updatePanelStyle/this.updateTimeoutId<@/home/daniel/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:95:55
setTimeout/<@/home/daniel/.local/share/gnome-shell/extensions/switcher@landau.fi/util.js:14:5

^C
daniel@dkdt:~$ 
```
After disabling the extension again, I get this:
![Screenshot from 2023-12-15 13-25-26](https://github.com/neuromorph/openbar/assets/62904593/d3f7373e-e38e-4aac-8510-6e0a049cd84e)

After logging out and back in, the error clears.

**Comment by in4matix** [comment] 2023-12-15 11:33
![Screenshot from 2023-12-15 13-32-25](https://github.com/neuromorph/openbar/assets/62904593/fccb8ce5-846c-449f-8413-d19d3c701524)

**Comment by neuromorph** [comment] 2023-12-15 11:53
OK, that looks like a bug. The items in the panel are dynamic (they come and go) and so resetting is getting tricky as I am working on the next update. This issue is also related to the same. 
I will fix it in the next update.

Thanks for reporting! 
Leave it disabled for now and enable once you get notified of the update.

**Comment by in4matix** [comment] 2023-12-15 11:57
Thanks for your assistance. Looking forward to the update.

**Comment by neuromorph** [comment] 2023-12-25 18:45
Quick update:
New version is almost ready in github g42-44 branch if you would like to try out (includes support for menus).
I would like to do a bit more tests and then submit to Gnome extensions-web. Also, the Gnome review might take some time before it can be published.
It should work fine but if you face any issues feel free to ping here.
Note: the default settings may not be good, as I haven't specifically set them yet (likely to be mostly just white color :)

**Comment by neuromorph** [comment] 2023-12-26 13:10
Update:
I have added more finishes and fixes in git and it is ready. Let me know if you try it out. I will iron out, in case any issues and then submit to Gnome extensions.

Thank you.

**Comment by neuromorph** [comment] 2023-12-28 06:33
New version is up now in Extensions web. You should also get an update notification from the Extensions app of Glass Grid.
Thus, I am closing this issue as resolved, if you face any problems please raise a new issue.
Thanks!

**Closed by neuromorph** 2023-12-28 06:33 UTC
