### ISSUE TITLE
[BUG]: Icons and some text are blurry

### ISSUE THREAD

**Issue by kzhe2059** [neuromorph/openbar#58] opened 2024-08-05 15:05 UTC
**Describe the bug**
Some icons and text in certain apps are blurry

**To Reproduce**
 Steps to reproduce the behavior: Enable GTK theming for everything

**Relevant  Specs:**
 - Open Bar version: 36
 - Gnome version: 46
 - OS/Distribution: Endeavour
 - Other installed extensions if interference is expected [Optional]: the problem goes away with disabling open shell and no other extensions appear related 

**Screenshots**
Helpful to see if there is a visual bug or if your Top Bar is modified by another extension that may be causing an interference.
![image](https://github.com/user-attachments/assets/197b0da5-4f0b-45b9-a6ee-165b74fbdce6)
![image](https://github.com/user-attachments/assets/2df46c62-dffc-49cb-b7bf-d3c3e1362a35)

**Error Stack Trace**
If you are getting an error (showing in the Extension Manager for e.g.), please run the following command in a terminal and then Enable the extension. If the error is preventing the extension from enabling then just remove and install the extension again while the command is running. If there is no error during enable then keep the command running and try disabling the extension. At some point the same error will show up in the terminal but it will also have a trace log. Please share that here so we can debug the issue.
`SHELL_DEBUG=all journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

**Comment by neuromorph** [comment] 2024-08-05 15:58
For apps, Open Bar only alters colors, toggle-switch icon, border and corner radius. It does not change font/size etc for any text or icon. Except for the Gnome Terminal app which includes some changes in headerbar buttons. 

In short, text/icon blur is unlikely in apps due to Open Bar. Typical causes, I would expect, are Display Scaling or font scaling that don't go well with each other.

What apps are you facing the issue in? and can you please provide screenshots showing the full app also, so I can see where the issue is occurring e.g. headerbar or content? 
How it looks with Open Bar On vs Off may also help.

Thanks.

**Comment by neuromorph** [comment] 2024-09-21 16:00
Closing the issue for lack of further details. 
If anyone comes across it and is facing a similar issue, feel free to log a new bug with details.

**Closed by neuromorph** 2024-09-21 16:00 UTC
