### ISSUE TITLE
Perfomance in Fullscreen with Dash to Dock

### ISSUE THREAD

**Issue by IronRUS** [neuromorph/openbar#27] opened 2024-04-07 14:31 UTC
How to reproduce it:

1. Install Dash to Dock
2. Turn it on and go to an app that opens fullscreen
3. Exit or minimize it

Distro: Nobara 39
Gnome 45.5

Note:
I dunno which settings cause this

[Screencast from 2024-04-07 17-17-46.webm](https://github.com/neuromorph/openbar/assets/38382271/00ac2778-1fd9-44b9-a8a2-dee1da7d7a70)

**Comment by neuromorph** [comment] 2024-04-08 18:04
Thank you for reporting!
I was able to reproduce the issue after some meddling. There are multiple sources at play contributing to it: 
- Gnome itself hides/shows panel with fullscreen on/off
- Blur my shell needs to do its own bit
- Open Bar also add to it

However, the main culprit is a 'wait' added to Open Bar for issue #20 (to allow extensions like Fullscreen Avoider to move the panel when in fullscreen). And the reason for that is the fact that Open Bar removes styling of bar when in fullscreen. And the root cause of all this is some issue in mutter which (used to?) cause Gnome shell to crash if an extension alters the panel and user locks the screen while in fullscreen. 
Good news is that, I am unable to reproduce the crash now and so it seems it has been fixed upstream. This issue affected all extensions that style the panel e.g. Blur my shell which still has the issue open. 

So, I have made it optional to keep or remove style in fullscreen. There is a new toggle in settings under Bar Props for 'Apply in fullscreen'. You should turn it On and your performance issue should go away. You need to get that update first. The update is currently in Github ('main' branch for Gnome 45+). You will need to manually install. You can just download and overwrite these files with those from Github:
- extension.js 
- prefs.js
- schemas/(both files in this directory)

Please also confirm the crash issue is fixed by trying these steps:
- Keep Open Bar styling enabled/On
- Keep 'Apply in fullscreen' option turned On in settings
- Open any app in fullscreen
- Lock the screen with Super + L

You should go to lock screen without any crash.

If all is well let me know. The next official update/release will include these fixes. I am working on more theming options, so it may take a while.

**Comment by IronRUS** [comment] 2024-04-09 20:41
Same issue after manually installation, If you don't have this problem, that means I have a problem specifically with Gnome/Mutter on my version or you need to do something that cause this issue but I haven't mentioned it. So, I should figure out what causes this problem, reproduce this again and report result! 

P.S. Sometimes I have problem with animations switching between workspaces.

**Closed** 2024-04-13 12:25 UTC
