### ISSUE TITLE
[BUG]: Bar height to 0 then up again causes crash

### ISSUE THREAD

**Issue by balintbarna** [neuromorph/openbar#53] opened 2024-06-30 08:23 UTC
**Describe the bug**
The entire gnome session crashes and you're thrown back to the log in screen.

**To Reproduce**
Set the top bar bar height to 0 with your scroll wheel, then up to 1-2-3-4-5, etc. 
I'm not sure about the reproduction rate but it happened to me a few times.

**Relevant  Specs:**
 - Open Bar version: nixfix
 - Gnome version: 46.2
 - OS/Distribution: NixOS
 - Other installed extensions if interference is expected [Optional]: Appindicator, Clipboard indicator, Fullscreen to empty workspace

**Comment by neuromorph** [comment] 2024-07-01 10:50
Good catch! Thank you for reporting!

Bar height of zero wouldn't fair well when Gnome's allocating it and can cause weirdness as you try to change it. I was able to reproduce the crash and it showed a memory access issue - segmentation fault. I have restricted the min height to 10 now since it is also already too low. I've also adjusted some timeout to avoid too many successive events when it is changed in that manner.

Works fine in my test so please try it out. 

Note: The `nixfix` branch is now merged into `main` along with all the fixes. So please install from `main` branch.

**Comment by neuromorph** [comment] 2024-07-09 12:14
New version of Open Bar with the fix is live on Gnome extensions, closing here.

**Closed by neuromorph** 2024-07-09 12:14 UTC
