### ISSUE TITLE
[BUG]: Can't seem to change the bar type

### ISSUE THREAD

**Issue by anshumanp12** [neuromorph/openbar#52] opened 2024-06-29 12:49 UTC
**Describe the bug**
I can't change the type of bar. It remains as a Floating type irrespective of the choice I make

**To Reproduce**
 Steps to reproduce the behavior: Select type of bar to anything but the type doesn't change

**Relevant  Specs:**
 - Open Bar version: 35
 - Gnome version: 46
 - OS/Distribution: Fedora 40
 - Other installed extensions if interference is expected [Optional]: 

**Screenshots**
https://github.com/neuromorph/openbar/assets/174189620/90f644b3-534e-465f-ab55-ec403f6318c9

**Comment by neuromorph** [comment] 2024-06-29 14:55
A bit weird. I am unable to reproduce so will need you to try a few things.

First of all, a reboot or logout/login might just fix it, possibly a one off quirk.
If not, let's check if there's any silent error happening. Please run following command in a terminal and then repeat the steps of enabling the extension and changing the Type of Bar. If the terminal shows any warnings/error, please report here:

`SHELL_DEBUG=all journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

Also, you can watch if the corresponding setting is being set, either in dconf or by running command below and then changing the Type of Bar:

`dconf watch /org/gnome/shell/extensions/openbar/ bartype`

Let me know what you find.

Thanks for reporting!
`

**Comment by anshumanp12** [comment] 2024-06-29 17:26
Yes it's indeed quite weird. I have been facing it for a few days already (after one of the recent updates) , so I have tried the logging out and shutting down etc. I even tried to re-install it and it didn't do anything. Here are the clips for the two commands you sent 

`SHELL_DEBUG=all journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

https://github.com/neuromorph/openbar/assets/174189620/502f64fa-5842-48ea-93cc-0db965435c58

I don't think there was anything relevant to the extension that popped on the screen. Also the dconf command did show that the bartype changes with any UI changes. Here is a record of that.

https://github.com/neuromorph/openbar/assets/174189620/8d05b148-ef63-48f2-be3b-e34f984d36d3

Please feel free to let me know if there's anything else you have in mind. I am not sure what would be an equivalent of a clean install for extensions, maybe I can try that.

**Comment by neuromorph** [comment] 2024-06-29 18:12
Thanks for the update. So the setting is getting set correctly but apparently the style isn't getting reloaded.

While no error from Open Bar, there seems to be quite a few from Blur My Shell and Dash-to-Dock. Can you please try disabling other extensions and only turn on Open Bar to test if it works? If so, we can then find where there may be any interference.

Another thing to try would be to uninstall and then download code from GitHub `main` branch and install it manually (instructions are in ReadMe). It has some fixes (unrelated), just in case. 

It got me curious so I just downloaded Fedora Workstation 40 iso and tried in a VM. Installed Open Bar there and it worked OK on a fresh install so there is likely some specific scenario e.g. interference with other extension that we need to find.

**Comment by anshumanp12** [comment] 2024-06-29 19:03
Tried all of it but didn't work. Disabled all the extensions and re-installed through github, still the same, I just realized that none of the changes I try get applied, e.g., changing the FG color of the bar from what to anything doesn't get reflected. 
Thanks for trying to help, but I guess, it's impossible for you to figure out without managing to reproduce this.

**Comment by neuromorph** [comment] 2024-06-30 06:20
> I just realized that none of the changes I try get applied, 

Are you using an immutable variant of the OS by any chance? That can prevent the stylesheet from getting regenerated. If so, you will need to try with the code from `nixfix` branch.

If that's not the case, you can replace the corresponding local installation files with the ones attached here
[obar_withLog_issue52.zip](https://github.com/user-attachments/files/16043444/obar_withLog_issue52.zip).
 I have added some log messages for debugging. You need to replace files, then log out and log in for it to take effect. After that, you can run this command as before to check for the log while changing the bartype:

`SHELL_DEBUG=all journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

**Comment by neuromorph** [comment] 2024-07-01 10:51
Update:
The `nixfix` branch is now merged into `main` along with all the other fixes. So please install from `main` branch for further tests.

**Comment by anshumanp12** [comment] 2024-07-03 17:57
So I tried the new installation files with the logs and got this
![Screenshot from 2024-07-03 23-19-30](https://github.com/neuromorph/openbar/assets/174189620/ed26d975-f583-45ad-8d15-22580577729d)
I don't use an immutable distro so even after trying the new install from the `main` branch, things are the same.

**Comment by neuromorph** [comment] 2024-07-03 18:26
Only the white text in the log is from OpenBar but that log is incomplete, in the sense that there are further steps about saving stylesheet and unloading+loading it that are missing. 
Please run the following commands to get and let me know the values of these settings:

`GSETTINGS_SCHEMA_DIR=$HOME/.local/share/gnome-shell/extensions/openbar@neuromorph/schemas gsettings get org.gnome.shell.extensions.openbar import-export`

`GSETTINGS_SCHEMA_DIR=$HOME/.local/share/gnome-shell/extensions/openbar@neuromorph/schemas gsettings get org.gnome.shell.extensions.openbar pause-reload`

**Comment by neuromorph** [comment] 2024-07-04 18:29
@anshumanp12 

Your issue is most likely fixed in the latest commit (few mins ago) in `main` branch.
You can try with that and let me know.

Thanks.

**Comment by anshumanp12** [comment] 2024-07-05 03:11
Yes, it worked! Thank you so much!!
Question though, everytime I have copied the `main` branch, the OpenBar version goes to 33. And it asks me to logout to update to the latest version (35). Let me know if I can do that without undoing what you have done.

Thanks again.

**Comment by neuromorph** [comment] 2024-07-05 03:24
Oh, version number needs to be updated. Once you download from 'main', open 'metadata.json' file and change the version to 35.
I will update in GitHub soon.

Happy that finally it is resolved :)
I will include the fix in the upcoming release.

**Comment by anshumanp12** [comment] 2024-07-05 03:52
Yeah. All good now. Thanks for all the help and patience.

**Closed** 2024-07-05 04:01 UTC
