### ISSUE TITLE
Volume icon scrolling action to adjust volume not working.

### ISSUE THREAD

**Issue by momoRaza** [neuromorph/openbar#73] opened 2024-09-15 20:47 UTC
Once the extension is activated, the ability to control volume by hovering the cursor over volume icon and scrolling the mouse wheel doesn't work.

**Comment by mkalinski** [comment] 2024-09-16 10:54
It's weirder than that.

For a few seconds (about 10 or so) after enabling the extension, the volume control by scrolling still works, but then it suddenly stops.

This happens after login, and any manual disabling and enabling the extension.

**Comment by neuromorph** [comment] 2024-09-16 12:15
Hey guys,

It is a bug introduced by the 'Enable Buttons Proximity' feature (under Top Bar Properties).
If you turn it off then the volume scrolling should work as before but the proximity feature would be off, of course. This new feature enabled interacting with the panel buttons from the paddings/margins as well, when applicable, thereby avoiding to pinpoint on the button but somehow the scroll event is not getting registered on the Volume icon. 
I will look into the issue and let you know.

Side Note:
There is another issue #72  reported on current update wherein their menu text is rendering broken/badly the kind that may happen with font/display scaling or NVIDIA and I was wondering if any of you are facing this issue since I am not able to reproduce it. If so, any inputs are welcome.

Thanks for reporting!

**Comment by momoRaza** [comment] 2024-09-16 17:55
Hi, yes switching Enable Buttons Proximity does fix the issue. As for the menu text, I'm on AMD RX 580 with 125% scaling and I'm not seeing any issues.
![Screenshot from 2024-09-16 12-45-44](https://github.com/user-attachments/assets/a9a8aa80-f9f0-472c-92e7-8da1ffcaa289)

**Comment by neuromorph** [comment] 2024-09-17 06:10
I have added a fix for this issue in the `main` branch that should allow the Volume scroll to work even with Proximity switch On. It is changed a bit though, the new version extends interaction zone for the buttons towards the screen edge to make it easier to click on them but not on the other side (i.e. below the buttons in top bar).
Let me know if it works fine or in case of any issues.

> As for the menu text, I'm on AMD RX 580 with 125% scaling and I'm not seeing any issues.

Thank you for the update! But I have a question, do you have 'Enable Menu Styles' switch On under 'Popup Menus'? I am curious since your screenshot looks close to the default style and apparently that rendering issue is presented when this option is turned On for them. 

Thanks!

**Comment by neuromorph** [comment] 2024-09-21 15:54
New version v41 with support for Gnome 47 is now live! It includes the fix for this issue as well.

Also:
> For a few seconds (about 10 or so) after enabling the extension, the volume control by scrolling still works, but then it suddenly stops.

It is 5 sec timeout after which the Proximity support feature is activated. Upon unlocking the screen, the panel gets populated by Gnome widgets and by extensions as well. Some app/extension can take 2-3 secs to finalize its button after OpenBar is enabled and so the timeout. 

And, FYI, the issue about text rendering is also fixed.

**Closed by neuromorph** 2024-09-21 15:54 UTC
