### ISSUE TITLE
[BUG]: wrong Bottom position of bar

### ISSUE THREAD

**Issue by skyxx** [neuromorph/openbar#56] opened 2024-07-18 10:01 UTC
**Describe the bug**
When set bottom position of bar its displayed only half of his height. Looks like problem with margin.
When i try setup bar height or margins it is showed on good position but when finished final position is with negative position to original.

**To Reproduce**
  - Simply choose Bottom position of bar in Top Bar Properties

**Relevant  Specs:**
 - Open Bar version:  36
 - Gnome version: 46.3.1
 - OS/Distribution: Majaro
 - Other installed extensions if interference is expected [Optional]: none

**Screenshots**
Helpful to see if there is a visual bug or if your Top Bar is modified by another extension that may be causing an interference.
![Screenshot from 2024-07-18 11-57-56](https://github.com/user-attachments/assets/831a0376-55d0-4cab-8e91-b491f09791dd)

**Error Stack Trace**
none

**Comment by neuromorph** [comment] 2024-07-18 14:50
Thank you for reporting!
I am however unable to reproduce it. I had tested on  Gnome 46 on Ubuntu and Fedora Workstation. I also launched a fresh VM now with Fedora WS 40 and updated it to Gnome 46.3.1 and installed Open Bar 36. It works as expected in Bottom position also. Expected behavior: it will be fully visible at bottom edge when margin is zero and will move up further from the edge when margin is increased.

I would need you to try a few things so we can try to narrow down where the issue might be coming from:

- Are there any other extensions that decide the position of the Bar e.g. Just Perfection? If so, can pls try with only Open Bar?
- Are you using multi-monitor setup? If so, can you pls try with only one?
- Are you using Display Scaling? If so, can you try with 100% scaling?
- If you have access to any other Distribution, can you pls try with it? I do not expect any issues with Manjaro but never used it either.

Thanks.

**Comment by skyxx** [comment] 2024-07-18 20:28
Hi, thank you for fast reply a and hints. 

I have notebook with high resolution and 200% scaling which is the issue.
Returning it to 100% bottom position is ok. Interesting is that Top position with high scaling is ok.

- tested also on Fedora with 200% scaling with same issue.
- i have disabled all extension which modify position
- no multi monitor setup

**Comment by neuromorph** [comment] 2024-07-19 18:39
Thank you for the update - the panel box position at bottom depends on its height which needs to scale with Display scaling.
I have added a fix to the GitHub `main` branch. Two files have been updated: `extension.js` and `stylesheets.js`.
You can replace these files in your local install with those from GitHub and try out.

Let me know how it goes.
Thanks.

**Comment by skyxx** [comment] 2024-07-21 18:09
Hi Neuromorph, changes helped. 
Thank you for quick fix. :)

**Comment by neuromorph** [comment] 2024-08-11 04:43
New version (v37) with the fix is now up on Gnome extensions web, closing here.

**Closed by neuromorph** 2024-08-11 04:43 UTC
