### ISSUE TITLE
Shell crash in full screen

### ISSUE THREAD

**Issue by Loup-Garou911XD** [neuromorph/openbar#26] opened 2024-04-03 20:58 UTC
The extension causes crash of the desktop environment kicking me to the desktop manager
distro: Arch Linux
Gnome version: 46
### Additional info:
I am using this plugin with dash-to-panel

# In full screen initially the effects of plugin are not loaded
![Screenshot from 2024-04-04 02-13-02](https://github.com/neuromorph/openbar/assets/90267658/269a9f22-620f-40ac-a66d-e097ea64b718)

# After changing the `BG Alpha (WMax)` under Bar Props:Window-Max the effects are loaded
[Screencast from 2024-04-04 02-13-31.webm](https://github.com/neuromorph/openbar/assets/90267658/504dcad9-c26a-4da9-a210-b81139d6d25f)
![Screenshot from 2024-04-04 02-12-40](https://github.com/neuromorph/openbar/assets/90267658/335e69d2-1f58-42c6-a0a5-ea34359b0a80)

After few seconds the shell crashes
Here are the logs from systemd journal
[log.txt](https://github.com/neuromorph/openbar/files/14858503/log.txt)

**Comment by neuromorph** [comment] 2024-04-04 09:24
Thank you for reporting!
I tried your steps but Not able to reproduce the crash. First, I couldn't get the panel to show in Fullscreen, but then I found an option in Dash-to-Panel settings under Intellihide to show the panel in fullscreen. I believe that is what you are using. 
The first part of Open Bar styles not applied in fullscreen are true and was added as a workaround for [another issue](https://github.com/neuromorph/openbar/issues/20#issuecomment-2006596382). That issue is about something off with Mutter which causes the shell to crash if there is some custom style applied to Panel and the screen is locked while in Fullscreen. To work around that issue, I watch for fullscreen and remove the styles and restore when not in fullscreen. This works fine without Dash-to-panel since the panel isn't available in fullscreen. 
This is the only crash I have encountered with this extension. (Note it was happening without this extension as well, so long you have styled the panel from any extension). So, I suppose this issue is also related. I have added a fix to the part introduced by last update to cater to it.

However, you want the styles to be applied while in fullscreen. And that would have been a bad idea due to the Mutter issue but things got a bit more weird. Not only that I couldn't reproduce crash in your scenario, I also could not reproduce it from the original scenario :open_mouth:  Earlier I could reproduce the crash in Gnome 42 (without the workaround) and it was also verified by another user in Gnome 45. So I suppose , the issue was fixed upstream.

In any case, for now I have made it optional to apply the styles or not while in fullscreen. There is a new toggle under Bar Props for 'Apply in Fullscreen'. Turning it On will give you the behavior you want. Please do this test, with the styles On in fullscreen, lock the screen and see if Gnome crashes and let me know. For me it doesn't anymore. 

In the end, you should now get the styles and no more crashes.
The update is currently in Github ('main' branch for Gnome 45+). You will need to manually install. You can just download and overwrite these files with those from Github:
- extension.js
- prefs.js
- schemas/(both files in this directory)

If all goes well, I will include this in the next official update.

**Comment by Loup-Garou911XD** [comment] 2024-04-04 18:12
Works!!! 🎉🎉🎉
[Screencast from 2024-04-04 23-41-03.webm](https://github.com/neuromorph/openbar/assets/90267658/72588862-52c5-4fbb-a0d5-d181fa670bcc)

**Comment by neuromorph** [comment] 2024-04-04 18:58
That's great! I hope you tried the lock screen on fullscreen test and no more crash. 
Someone just reported Gnome 46 crashing with Blur My Shell by locking screen even in Overview/App-grid :eyes:

**Comment by Loup-Garou911XD** [comment] 2024-04-04 19:01
> That's great! I hope you tried the lock screen on fullscreen test and no more crash. 
> Someone just reported Gnome 46 crashing with Blur My Shell by locking screen even in Overview/App-grid :eyes: 
> 

Yeah that works aswell!

**Comment by neuromorph** [comment] 2024-06-20 14:21
The fix is now part of the live version published in E.G.O. (Gnome Extensions web), so closing this issue.

**Closed by neuromorph** 2024-06-20 14:21 UTC
